server:
  port: ${PORT:8081}

spring:
  application:
    name: product-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/product-db
    username: admin
    password: 123456
    initialization-mode: always
    initiliaze: true
    continue-on-error: true
    platform: postgresql
    max-active: 3

  jpa:
    hibernate:
      ddl-auto: create-drop
      format-sql: true
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQL14Dialect

app-config:
  secrets:
    api-secret: ${API_SECRET:YXV0aC1hcGktc2VjcmV0LWRldi0xMjM0NTY=}