INSERT INTO CATEGORY (ID, CATEGORY_DESCRIPTION) VALUES (1, 'Comic Books');
INSERT INTO CATEGORY (ID, CATEGORY_DESCRIPTION) VALUES (2, 'Movie');
INSERT INTO CATEGORY (ID, CATEGORY_DESCRIPTION) VALUES (3, 'Books');

INSERT INTO SUPPLIER (ID, SUPPLIER_NAME) VALUES (1, 'Panini Comics');
INSERT INTO SUPPLIER (ID, SUPPLIER_NAME) VALUES (2, 'Amazon');

INSERT INTO PRODUCT (ID, PRODUCT_NAME, FK_SUPPLIER, FK_CATEGORY, PRODUCT_QUANTITY_AVAILABLE) VALUES (1, 'Crise nas Infinitas Tarras', 1, 1, 10);

INSERT INTO PRODUCT (ID, PRODUCT_NAME, FK_SUPPLIER, FK_CATEGORY, PRODUCT_QUANTITY_AVAILABLE) VALUES (2, 'Interestelar', 2, 2, 5);

INSERT INTO PRODUCT (ID, PRODUCT_NAME, FK_SUPPLIER, FK_CATEGORY, PRODUCT_QUANTITY_AVAILABLE) VALUES (3, 'Harry Potter e a Pedra Filosofal', 2, 3, 3);