INSERT INTO CATEGORY (ID, CATEGORY_DESCRIPTION) VALUES (1000, 'Comic Books');
INSERT INTO CATEGORY (ID, CATEGORY_DESCRIPTION) VALUES (1001, 'Movie');
INSERT INTO CATEGORY (ID, CATEGORY_DESCRIPTION) VALUES (1002, 'Books');

INSERT INTO SUPPLIER (ID, SUPPLIER_NAME) VALUES (1000, 'Panini Comics');
INSERT INTO SUPPLIER (ID, SUPPLIER_NAME) VALUES (1001, 'Amazon');

INSERT INTO PRODUCT (ID, PRODUCT_NAME, FK_SUPPLIER, FK_CATEGORY, PRODUCT_QUANTITY_AVAILABLE) VALUES (1000, 'Crise nas Infinitas Tarras', 1000, 1000, 10);

INSERT INTO PRODUCT (ID, PRODUCT_NAME, FK_SUPPLIER, FK_CATEGORY, PRODUCT_QUANTITY_AVAILABLE) VALUES (1001, 'Interestelar', 1001, 1001, 5);

INSERT INTO PRODUCT (ID, PRODUCT_NAME, FK_SUPPLIER, FK_CATEGORY, PRODUCT_QUANTITY_AVAILABLE) VALUES (1002, 'Harry Potter e a Pedra Filosofal', 1001, 1002, 3);